title: Anand Nande
logo: /elements/img/me.png
description:  OpenStack Architect | Kubernetes | CI/CD | GitOps | Linux | Ansible 
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: http://example.com/download.zip