title: Anand Nande
logo: /assets/img/me2.png
description:  OpenStack Architect | Kubernetes | CI/CD | GitOps | Linux | Ansible 
theme: jekyll-theme-minimal
show_downloads: true
github:
  #zip_url: https://github.com/anande/portfolio/blob/main/assets/files/ANAND_NANDE.pdf
  pdf_url: https://raw.githubusercontent.com/anande/portfolio/main/assets/files/ANAND_NANDE.pdf